name: Create and publish a Docker image

on:
  schedule:
    # Set the cron schedule to check for updates periodically (e.g., daily)
    - cron: '0 0 * * *'
  workflow_dispatch: # Optionally, allow manual triggering
    inputs:
      manual_trigger:
        description: 'Manually trigger the update check'
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_URL_API: https://api.github.com/repos/marcrobledo/RomPatcher.js/releases/latest

jobs:
  check-for-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check for new tag
        id: check-tag
        run: |
          latest_tag=$(curl -s ${REPO_URL_API} | grep -oP '(?<=tag\/v)[^"]+')
          if [[ -n "$latest_tag" ]]; then
            echo "::set-output name=upstream_tag::$latest_tag" # Change to UPSTREAM_TAG
          else
            echo "No new tag found."
          fi

      - name: Set UPSTREAM_TAG
        if: steps.check-tag.outputs.upstream_tag != '' || github.event.inputs.manual_trigger # Change to UPSTREAM_TAG
        run: |
          if [[ -n "${{ steps.check-tag.outputs.upstream_tag }}" ]]; then # Change to UPSTREAM_TAG
            echo "UPSTREAM_TAG=${{ steps.check-tag.outputs.upstream_tag }}" >> $GITHUB_ENV # Change to UPSTREAM_TAG
          fi

      - name: Create and publish a Docker image
        if: steps.check-tag.outputs.upstream_tag != '' || github.event.inputs.manual_trigger # Change to UPSTREAM_TAG
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ${{ env.UPSTREAM_TAG }} # Change to UPSTREAM_TAG
          labels: ${{ steps.meta.outputs.labels }}
