name: Create and publish a Docker image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the update check'
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_URL_API: https://api.github.com/repos/marcrobledo/RomPatcher.js/releases/latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for new tag
        id: check-tag
        run: |
          latest_tag=$(curl -s ${REPO_URL_API} | jq -r '.tag_name')
          if [[ -n "$latest_tag" ]]; then
            echo "::set-output name=upstream_tag::$latest_tag"
          else
            echo "No new tag found."
          fi

      - name: Set UPSTREAM_TAG
        if: steps.check-tag.outputs.upstream_tag != '' || github.event.inputs.manual_trigger
        run: |
          if [[ -n "${{ steps.check-tag.outputs.upstream_tag }}" ]]; then
            echo "UPSTREAM_TAG=${{ steps.check-tag.outputs.upstream_tag }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image with padded tag
        run: |
          # Get the UPSTREAM_TAG from environment variables
          UPSTREAM_TAG=${{ env.UPSTREAM_TAG }}

          # Check if UPSTREAM_TAG has the 'v' prefix, and if not, add it
          if [[ "$UPSTREAM_TAG" != v* ]]; then
            UPSTREAM_TAG="v$UPSTREAM_TAG"
          fi

          # Check if UPSTREAM_TAG has three parts (e.g., "v2.7"), and if not, add ".0"
          if [[ $UPSTREAM_TAG != v[0-9].[0-9].[0-9] ]]; then
            UPSTREAM_TAG="$UPSTREAM_TAG.0"
          fi

          # Build and push the Docker image with the padded tag
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${UPSTREAM_TAG}" .
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${UPSTREAM_TAG}"
